"""Deterministic compiler backends. No provider is imported or called here."""

import ast
from typing import Protocol

from nlpipe.catalog import Catalog
from nlpipe.explanation import explain
from nlpipe.ir import PipelineSpec, canonical, digest
from nlpipe.validation import require_valid


class Backend(Protocol):
    def compile(self, spec: PipelineSpec, catalog: Catalog) -> str: ...


def compile_airflow(spec: PipelineSpec, catalog: Catalog) -> str:
    spec = require_valid(spec, catalog)
    encoded = canonical(spec)
    task_rows = []
    symbols = {t.id: f"node_{i}" for i, t in enumerate(spec.tasks)}
    for task in spec.tasks:
        dependencies = [ref[5:] for ref in task.inputs if ref.startswith("task:")]
        upstream = "{" + ", ".join(repr(key) + ": " + symbols[key] for key in dependencies) + "}"
        task_rows.append(
            f"    {symbols[task.id]} = run_step.override(task_id={task.id!r}, "
            f"retries={task.retries if task.retries is not None else spec.retry_policy.retries}, "
            f"execution_timeout=timedelta(seconds={task.timeout or spec.timeout_policy.task_seconds}))"
            f"({task.id!r}, {upstream})"
        )
    for task in spec.tasks:
        for upstream in task.dependencies:
            task_rows.append(f"    {symbols[upstream]} >> {symbols[task.id]}")
    timeout = min(
        [spec.timeout_policy.pipeline_seconds, *[s.max_duration_seconds for s in spec.slas]]
    )
    code = f"""# Generated by nlpipe 0.1.0. Inspect IR; never hand-edit this artifact.
# IR SHA-256: {digest(spec)}
import json
from datetime import timedelta
import pendulum
from airflow.sdk import DAG, task, get_current_context
from nlpipe.runtime import airflow_execute, airflow_notify

SPEC = json.loads({encoded!r})
CATALOG_HASH = {digest(catalog)!r}

def notify_failure(context):
    airflow_notify(SPEC, CATALOG_HASH, "failure", context)

def notify_success(context):
    airflow_notify(SPEC, CATALOG_HASH, "success", context)

@task
def run_step(task_id, upstream):
    context = get_current_context()
    return airflow_execute(SPEC, CATALOG_HASH, task_id, upstream,
                           context["run_id"], (context.get("data_interval_end") or
                           context.get("logical_date") or context["dag_run"].run_after).isoformat())

with DAG(
    dag_id={spec.pipeline_id!r},
    schedule={spec.schedule.cron!r},
    start_date=pendulum.parse({spec.start_date.isoformat()!r}).in_timezone({spec.timezone!r}),
    catchup={spec.catchup!r},
    max_active_runs=1,
    max_active_tasks={spec.concurrency},
    dagrun_timeout=timedelta(seconds={timeout}),
    tags={spec.tags!r},
    doc_md={explain(spec)!r},
    default_args={{"owner": {",".join(spec.owners) or "unassigned"!r},
                  "retry_delay": timedelta(seconds={spec.retry_policy.delay_seconds}),
                  "retry_exponential_backoff": {spec.retry_policy.exponential_backoff!r}}},
    on_failure_callback=notify_failure,
    on_success_callback=notify_success,
) as dag:
{chr(10).join(task_rows)}
"""
    ast.parse(code)
    return code
